group_id: 1
expert_group_name: "exp_dummy"
data:
  dataset_sources:
    - path: "allenai/c4"
      name: "en"
      weight: 0.5
      text_column: "text"
    - path: "nvidia/Nemotron-CC-Math-v1"
      name: "4plus"
      weight: 0.5
      text_column: "text"
  batch_size: 4 
  sequence_length: 100
  world_size: 10 # TODO: approximately how many miners are out there
  rank: 1 # TODO: based on your uid
  dataset_class: "expert_groups.exp_math.dataset:StreamingTorchDataset"